### ISSUE TITLE
 Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by arihantverma** [markshapiro/webpack-merge-and-include-globally#12]
The file that is being minified is large, and this error is thrown. I'm using — https://github.com/markshapiro/webpack-merge-and-include-globally#transform — to minify the code as shown in the README.md

**Comment by markshapiro** [comment]
can this be minify library issue? does it throw error when you don't transform?

**Comment by arihantverma** [comment]
I think this is the minify library (`uglify-js`'s minify). I'm trying make sure of it though. I'll update when I do.

**Comment by gdad-s-river** [comment]
It is a problem with the minifier itself. I had the liberty to switch minifier to `babel-minifier`, hence I did.

**Comment by arihantverma** [comment]
It is a problem with the minifier itself. I had the liberty to switch minifier to `babel-minifier`, hence I did. This issue can be closed.
