### ISSUE TITLE
Issue in minifying the js bundle files 

### ISSUE THREAD

**Issue by mianRafay** [markshapiro/webpack-merge-and-include-globally#13]
Hi, I am facing the issue in minifying of js files. 
Here is my code : 

const path = require("path")
const webpack = require("webpack")
const UglifyJsPlugin = require("uglifyjs-webpack-plugin")
const uglifyJS = require("uglify-js");
const MergeIntoSingleFilePlugin = require('webpack-merge-and-include-globally');
const fs = require('fs');

module.exports = {
    entry: {
       
        controllers: [
            "./wwwroot/docs/controllers/accountCtrl.js",
            "./wwwroot/docs/controllers/ribbonCtrl.js",
            "./wwwroot/docs/controllers/addConnectionDialogCtrl.js",
            "./wwwroot/docs/controllers/aggregationDialogCtrl.js",
            "./wwwroot/docs/controllers/aggregationLevelCtrl.js",
            "./wwwroot/docs/controllers/attributesCtrl.js",
            "./wwwroot/docs/controllers/attributesDialogCtrl.js",
            "./wwwroot/docs/controllers/calendarCtrl.js",
            "./wwwroot/docs/controllers/calendarPanelCtrl.js",
            "./wwwroot/docs/controllers/connectionsDataCtrl.js",
            "./wwwroot/docs/controllers/corpCalOptionsCtrl.js",
            "./wwwroot/docs/controllers/externalDataConfigCtrl.js",
            "./wwwroot/docs/controllers/fieldsDialogCtrl.js",
            "./wwwroot/docs/controllers/forecastCtrl.js",
            "./wwwroot/docs/controllers/forecastPanelCtrl.js",
            "./wwwroot/docs/controllers/hierarchyStructureCtrl.js",
            "./wwwroot/docs/controllers/historyDemandCtrl.js",
            "./wwwroot/docs/controllers/mappingDataCtrl.js",
            "./wwwroot/docs/controllers/messagePanelCtrl.js",
            "./wwwroot/docs/controllers/navigationTreeCtrl.js",
            "./wwwroot/docs/controllers/newConnectionsDialogCtrl.js",
            "./wwwroot/docs/controllers/productDataCtrl.js",
            "./wwwroot/docs/controllers/propertiesCtrl.js",
            "./wwwroot/docs/controllers/selectionPanelCtrl.js",
            "./wwwroot/docs/controllers/staggedDataCtrl.js",
            "./wwwroot/docs/controllers/uiRoutingCtrl.js",
            "./wwwroot/docs/controllers/unitofMeasuresCtrl.js",
            "./wwwroot/docs/controllers/wahupaCalendarCtrl.js",
            "./wwwroot/js/Modules/Designer/progressBarCtrl.js"
        ]
    },
    output: {
        filename: "[name].bundle.js",
        path: path.join(__dirname + "/wwwroot", "dist")
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules)/,
                use: {
                    loader: "babel-loader",
                    options: {
                        presets: ["env"]
                    }
                }
            }
        ]
    },
    plugins: [
      
        new MergeIntoSingleFilePlugin({
            files: [{
              src:[
                './wwwroot/js/Modules/Designer/core.js',
                './wwwroot/js/Modules/Designer/init.js',
                './wwwroot/js/Modules/Designer/storageMgr.js',
                './wwwroot/js/Modules/Designer/designer.js',
                './wwwroot/js/Modules/Designer/userActions.js',
                './wwwroot/js/Modules/Designer/tabObject.js',
                './wwwroot/js/Modules/Designer/tabServiceObject.js',
                './wwwroot/js/Modules/Designer/layoutServiceObject.js',
                './wwwroot/js/Modules/Designer/zoomServiceObject.js',
                './wwwroot/js/Modules/Designer/modelDrawingObject.js',
                './wwwroot/js/Modules/Designer/corpCalendarServiceObject.js',
                './wwwroot/js/Modules/Designer/planningCalendarObject.js',
                './wwwroot/js/Modules/Designer/historyObject.js',
                './wwwroot/js/Modules/Designer/integrationObject.js',
                './wwwroot/js/Modules/Designer/wahupaCalendarObject.js',
                './wwwroot/js/Modules/Designer/unitOfMeasureObject.js',
                './wwwroot/js/Modules/Designer/aggregationLevelObject.js',
                './wwwroot/js/Modules/Designer/hierarchyStructureObject.js',
                './wwwroot/js/Modules/Designer/productDataObject.js',
                './wwwroot/js/Modules/Designer/attributesObject.js',
                './wwwroot/js/Modules/Designer/connectionsObject.js',
                './wwwroot/js/Modules/Designer/fieldObject.js',
                './wwwroot/js/Modules/Designer/dataConfigurationObject.js',
                './wwwroot/js/Modules/Designer/staggedDataObject.js',
                './wwwroot/js/Modules/Designer/mappingDataObject.js',
                './wwwroot/js/Modules/Designer/fileUpload.js',
                './wwwroot/js/Modules/Designer/forecastActions.js',
                './wwwroot/js/Modules/Designer/foundationEntitiesObject.js',
                './wwwroot/js/Modules/Designer/aggregatedFieldsObject.js',
                './wwwroot/js/Modules/Designer/foundationFieldsObject.js',
                './wwwroot/js/Modules/Designer/optimizationsObject.js',
                './wwwroot/js/Modules/Designer/planningEntitiesObject.js',
                './wwwroot/js/Modules/Designer/planningFieldsObject.js',
                './wwwroot/js/Modules/Designer/planningLevelsObject.js'
              ],
              dest: code => {
                const min = uglifyJS.minify(code, {sourceMap: {
                    filename: 'designer.bundle.js',
                    url: 'designer.bundle.js.map'
                  }});
                return {
                  'designer.bundle.js':min.code,
                  'designer.bundle.js.map': min.map,
                }
              },
            }],
        }),
        new UglifyJsPlugin()
    ]
}

Here is the error: 

![image](https://user-images.githubusercontent.com/21196285/48759644-9a863800-ecc5-11e8-9df5-c391c75fe0ea.png)

**Comment by markshapiro** [comment]
can you try to use `new AddAssetPlugin('designer.bundle.js', '')` to isolate the problem in order to know whether the plugin throws the error?

**Comment by mianRafay** [comment]
Thanks for the reply. The problem was with the uglify js plugin. It's all good now. 👍
