### ISSUE TITLE
Peer dependency needs a version

### ISSUE THREAD

**Issue by richardowen** [markshapiro/webpack-merge-and-include-globally#14]
The peer dependency created in a94abd27b7f29367c917caf9c78bb597916b456f needs to specify a version. When installing the package, we now get the following error even though we have the latest version of webpack installed (4.28.2):

```npm WARN webpack-merge-and-include-globally@2.1.9 requires a peer of webpack@ but none is installed. You must install peer dependencies yourself.```

Perhaps it would be best to pin the major version v4? Following semver like this is suggested in the Node.js documentation:

https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by markshapiro** [comment]
it had to be `>= 1.0.0` as I want to retain all versions, confused with ``, works for me, can you check?

**Comment by richardowen** [comment]
Yep, v2.1.11 is working fine. Thanks!
