### ISSUE TITLE
refresh on change 

### ISSUE THREAD

**Issue by marc0n3** [markshapiro/webpack-merge-and-include-globally#21]
Hi,
first of all thank for your work.
I was just wondering if there is a way to refresh the merge output on file change without relaunching webpack-dev-server.

I'm using webpack 4

Thanks in advance
Marco

**Comment by markshapiro** [comment]
@marc0n3 do you mean without manually relaunching or without auto reloader?
I'm not expert on this but doesn't webpack have partial bundling of changes?

**Comment by marc0n3** [comment]
Yes, it has.
Actually I'm using it with webpack dev server that keep the file new.
What I see is that if I change a file packed with your plugin, the page don't get reloaded.
If, after that, I change a file in the main webpack bundle, page is reloaded, bundle re-emitted and the new content generated by your plugin is provided

**Comment by markshapiro** [comment]
@marc0n3 Hi, sorry was away, my hand was healing, if I understood correctly you're describing actually 2 problems right?
1. page is not reloaded if only file inside the bundle was changed
2. if you only change some file outside the bundled list, the bundled content is regenerated without purpose and causes lag
correct?

**Comment by markshapiro** [comment]
@marc0n3 added `chunks` parameter to run plugin only for listed entry points
``` javascript
entry: {
	main: [ ... ],
	yourGlobalBundledCode: ['./file1.js', './file2.js', ... ], // <-- all files that should trigger rebundle
},
plugins: [
	new MergeIntoSingle({
		...
		chunks: ['yourGlobalBundledCode'], // <-- entry name for which this should bundle
	})
]
```
this will cause refresh when files under `yourGlobalBundledCode` entry point changed and will not run plugin if files under `main` entry point changed

**Comment by marc0n3** [comment]
Hi @markshapiro,
sorry, I'm quite busy on another project right now, I'll try it as soon as possible.
Thanks for your work,
Marco

**Comment by marc0n3** [comment]
Hi @markshapiro,
I concluded that my project is too complex to find out if the problem is related to your plugin, it seems to work now, by limiting updates just to the required chunk, but actually priority order changes so files seem to be not included if I rebuild other chuncks and not yourGlobalBundleCode.
I suspect this to be related to the complexity of my project so I close the issue
