### ISSUE TITLE
v2.2.2 [webpack-cli] TypeError: Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by johnhunter** [markshapiro/webpack-merge-and-include-globally#56]
Upgrading from 2.1.26 to 2.2.2 causes a Webpack 4 build failure.

Webpack version: webpack@4.44.2 webpack-cli@4.3.1 
Node version: v12.16.3

Error: `[webpack-cli] TypeError: Cannot read property 'tap' of undefined`
at [index.node6-compatible.js:273:55](https://github.com/markshapiro/webpack-merge-and-include-globally/blob/master/index.node6-compatible.js#L273)

Fails with webpack-merge-and-include-globally 2.2.2 and 2.2.1. 
Builds ok with 2.1.26

**Comment by markshapiro** [comment]
@johnhunter thanks for notifying, I've managed to reproduce it with webpack 4, i just published the fix

**Comment by johnhunter** [comment]
@markshapiro thanks for the quick turnaround!

**Comment by johnhunter** [comment]
Confirmed resolved in version 2.2.3
