### ISSUE TITLE
Not working for empty entry point

### ISSUE THREAD

**Issue by ayush000** [markshapiro/webpack-merge-and-include-globally#57]
I'm using this plugin with webpack 5.10.0. In v2.1.26, if I specify an empty entry point in webpack config, the concatenated file is generated in the output directory. This is not the case with v2.2.3. E.g.

```
module.exports = {
  entry: {},
  output: {
    path: "..."
  },
  plugins: [
    new CleanWebpackPlugin({
      verbose: true
    }),
    // Used to merges all libs into single bundle
    new MergeIntoSingleFilePlugin({
      files: {
        "filename.min.js": ["file1path", "file2path"]
      }
    })
}
```

The above snippet generates `filename.min.js` for v2.1.26 but doesn't generate the file for v2.2.3. Is this expected change or a bug?

**Comment by markshapiro** [comment]
@ayush000 a bug resulting from fix of webpack 5 support, just fixed & published

**Comment by ayush000** [comment]
Thanks. Working now
