### ISSUE TITLE
unable to search recursively

### ISSUE THREAD

**Issue by KalyanAsula** [markshapiro/webpack-merge-and-include-globally#6]
The plugin works good for non recursive search of files but encountering an error  while using the search like  ./src/**/*.js  

Error : "asset optimizationTypeError: Cannot read property 'length' of undefined
    at Object.size (C:\Users\kkasula\Documents\Workspace-2.0\2.0\node_modules\webpack-merge-and-include-globally\index.js"

**Comment by markshapiro** [comment]
I couldn't reproduce it and the example already includes recursion (jquery/**/*.min.js), do you use any transform option? the error can happen if transform returns null.

**Comment by KalyanAsula** [comment]
Yes, You are right. The issue with transform code snippet. It works good when I comment out the transform code snippet. Below is the code snippet,

transform: {
            'js/2.0.js': code => require("uglify-js").minify(code).code
          }

Could you please let me know where it went wrong in this snippet.

**Comment by markshapiro** [comment]
it happened to me with invalid js code such as "{{" "#"
