### ISSUE TITLE
How to run this plugin only once after webpack init?

### ISSUE THREAD

**Issue by 7iomka** [markshapiro/webpack-merge-and-include-globally#7]
How to run this plugin only once after webpack init?
I have problem - on a progect I use browsersync and it inject changes after any change in css files.
This plugin emit event and change js instance http://s1.micp.ru/H69uG.jpg
 (in my case in files object i have 2 files: 1 - node module, 2 - my custom script, and in transform object i have babel.transform function)
See screenshot: http://s3.micp.ru/T6mD2.jpg

Without this plugin I not any js file emit, when I make changes in css files.
Thanks for any help!

**Comment by markshapiro** [comment]
can you provide callback to browsersync when it finishes? this way you can call again webpack with this plugin.

**Comment by 7iomka** [comment]
what do you mean by words "callback to browsersync when it finishes"?
I use webpack-synchronizable-shell-plugin for watching onBuildEnd of webpack, then I run express server, and init browsersync instance with proxy to the express server, after that, i run watchers of all needed files
(https://i.imgur.com/Fbs4e6V.jpg)
What can I do to prevent the script, formed by your plugin from being updated every time when I save styles?
Аt the moment I can not use the plugin because of this, and I have to enable it only on production, but it's inconvenient, because if it was a critical file (an compilation of critical vendors), I would not know what to do.
I will be grateful for any advice!

**Comment by markshapiro** [comment]
does the `bs.reload` trigger new webpack run everytime a file changed? or is the plugin somehow re-runing automatically? from what i understood, you want to compile your files only 1 time, without re-running my plugin each time the the files of `browser-testing.min.js` were changed, right?

**Comment by 7iomka** [comment]
bs reload make this: https://browsersync.io/docs/api#api-reload
In another words, im my cas, bs inject css changes directly in browser, without full page-reload; Webpack watching css/scss files, and make some things with plugins sass-loader, css-loader, post-css-loader, etc..
When I save css file, webpack make css code and paste in buld directory, but browsersync watch this directory, and inject new compiled css file in the browser;
Your plugin emit changes in js file in all moments, independed of type of file I changed, and this is bad behaviour! 
So I want at least to run your plugin only once, without re-running it every time the listed files under browser-testing.min.js were changed, right, BUT:
it would be logical that this happens only when I make changes not in any files, but in the files that are included in this script!
Thanks!

**Comment by markshapiro** [comment]
are you webpack watchers too? can this https://www.npmjs.com/package/run-once-plugin help maybe?

**Comment by 7iomka** [comment]
Thank you, man!
It works!
https://i.imgur.com/8F7p9yS.jpg
this workaround seems to me to be written somewhere in the documentation in your plug-in, otherwise with a similar problem (especially HMR) and other means of tracking changes, users will have problems)
If you think the problem is exhausted - close this issue)
